# Assignment 10 (Recommendation System) book dataset

## Q.  Problem statement. Build a recommender system by using cosine simillarties score.

In [1]:
# Importing Libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
# Loading The Dataset
books_df = pd.read_csv('book.csv',encoding='latin1')
books_df

Unnamed: 0  User.ID                                         Book.Title  \
0              1   276726                                Classical Mythology   
1              2   276729                                       Clara Callan   
2              3   276729                               Decision in Normandy   
3              4   276736  Flu: The Story of the Great Influenza Pandemic...   
4              5   276737                             The Mummies of Urumchi   
5              6   276744                             The Kitchen God's Wife   
6              7   276745  What If?: The World's Foremost Military Histor...   
7              8   276747                                    PLEADING GUILTY   
8              9   276747  Under the Black Flag: The Romance and the Real...   
9             10   276747            Where You'll Find Me: And Other Stories   
10            11   276747                        Nights Below Station Street   
11            12   276747  Hitler's Secret Bankers: The Myth of Swiss Neu...   
12            13   276748                                 The Middle Stories   
13            14   276751                                           Jane Doe   
14            15   276754  A Second Chicken Soup for the Woman's Soul (Ch...   
15            16   276755       The Witchfinder (Amos Walker Mystery Series)   
16            17   276760  More Cunning Than Man: A Social History of Rat...   
17            18   276762                      Goodbye to the Buttermilk Sky   
18            19   276762                                      The Testament   
19            20   276762               Beloved (Plume Contemporary Fiction)   
20            21   276762  Our Dumb Century: The Onion Presents 100 Years...   
21            22   276768  New Vegetarian: Bold and Beautiful Recipes for...   
22            23   276772  If I'd Known Then What I Know Now: Why Not Lea...   
23            24   276772  Mary-Kate &amp; Ashley Switching Goals (Mary-K...   
24            25   276772                       Tell Me This Isn't Happening   
25            26   276774                           Flood : Mississippi 1927   
26            27   276780                                        Wild Animus   
27            28   276780                                           Airframe   
28            29   276786                                           Timeline   
29            30   276786                           OUT OF THE SILENT PLANET   
...          ...      ...                                                ...   
9970        9971   162063                        Five Quarters of the Orange   
9971        9972   162068        Craig Claibornes: A Feast Made for Laughter   
9972        9973   162085                                      Stallion Gate   
9973        9974   162085                                          To Asmara   
9974        9975   162085  Murder and Spies, Lovers and Lies: Settling th...   
9975        9976   162091                               The Living : A Novel   
9976        9977   162092                           Your Oasis on Flame Lake   
9977        9978   162092                                       The Handyman   
9978        9979   162092                                             Cherry   
9979        9980   162092                                Tending to Virginia   
9980        9981   162092             Victory Over Japan : A Book of Stories   
9981        9982   162095                             Lempriere's Dictionary   
9982        9983   162095                                Eucalyptus: A Novel   
9983        9984   162095                               Dogless in Metchosin   
9984        9985   162095                       Hen's Teeth and Horse's Toes   
9985        9986   162095               Why We Buy : The Science Of Shopping   
9986        9987   162103                                  Slowness: A Novel   
9987        9988   162107                            What's Bred in the Bone   
9988  

In [3]:
books_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
Unnamed: 0     10000 non-null int64
User.ID        10000 non-null int64
Book.Title     10000 non-null object
Book.Rating    10000 non-null int64
dtypes: int64(3), object(1)
memory usage: 312.6+ KB


In [4]:
books_df.isnull().sum()

Unnamed: 0     0
User.ID        0
Book.Title     0
Book.Rating    0
dtype: int64

In [5]:
books_df1 = books_df.drop('Unnamed: 0',axis=1)

In [6]:
books_df1

User.ID                                         Book.Title  Book.Rating
0      276726                                Classical Mythology            5
1      276729                                       Clara Callan            3
2      276729                               Decision in Normandy            6
3      276736  Flu: The Story of the Great Influenza Pandemic...            8
4      276737                             The Mummies of Urumchi            6
5      276744                             The Kitchen God's Wife            7
6      276745  What If?: The World's Foremost Military Histor...           10
7      276747                                    PLEADING GUILTY            9
8      276747  Under the Black Flag: The Romance and the Real...            9
9      276747            Where You'll Find Me: And Other Stories            8
10     276747                        Nights Below Station Street            7
11     276747  Hitler's Secret Bankers: The Myth of Swiss Neu...            7
12     276748                                 The Middle Stories            6
13     276751                                           Jane Doe            8
14     276754  A Second Chicken Soup for the Woman's Soul (Ch...            8
15     276755       The Witchfinder (Amos Walker Mystery Series)            5
16     276760  More Cunning Than Man: A Social History of Rat...           10
17     276762                      Goodbye to the Buttermilk Sky            5
18     276762                                      The Testament            8
19     276762               Beloved (Plume Contemporary Fiction)            3
20     276762  Our Dumb Century: The Onion Presents 100 Years...            4
21     276768  New Vegetarian: Bold and Beautiful Recipes for...            4
22     276772  If I'd Known Then What I Know Now: Why Not Lea...            7
23     276772  Mary-Kate &amp; Ashley Switching Goals (Mary-K...           10
24     276772                       Tell Me This Isn't Happening           10
25     276774                           Flood : Mississippi 1927            9
26     276780                                        Wild Animus            7
27     276780                                           Airframe            7
28     276786                                           Timeline            6
29     276786                           OUT OF THE SILENT PLANET            8
...       ...                                                ...          ...
9970   162063                        Five Quarters of the Orange            5
9971   162068        Craig Claibornes: A Feast Made for Laughter            8
9972   162085                                      Stallion Gate            6
9973   162085                                          To Asmara            5
9974   162085  Murder and Spies, Lovers and Lies: Settling th...            7
9975   162091                               The Living : A Novel            9
9976   162092                           Your Oasis on Flame Lake            7
9977   162092                                       The Handyman            6
9978   162092                                             Cherry            5
9979   162092                                Tending to Virginia            5
9980   162092             Victory Over Japan : A Book of Stories            9
9981   162095                             Lempriere's Dictionary            9
9982   162095                                Eucalyptus: A Novel            9
9983   162095                               Dogless in Metchosin            8
9984   162095                       Hen's Teeth and Horse's Toes            8
9985   162095               Why We Buy : The Science Of Shopping            8
9986   162103                                  Slowness: A Novel            7
9987   162107                            What's Bred in the Bone            7
9988   162109                            The Flower in the Skull           10
9989   162113       The Cape

In [7]:
books_df1.describe()

User.ID  Book.Rating
count   10000.000000  10000.00000
mean    95321.249800      7.56630
std    117645.703609      1.82152
min         8.000000      1.00000
25%      2103.000000      7.00000
50%      3757.000000      8.00000
75%    162052.000000      9.00000
max    278854.000000     10.00000

In [8]:
# Implementing Count Vectorizer
cv = CountVectorizer()
count_matrix = cv.fit_transform(books_df1)
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 1 0 0 1]
 [1 0 0 1 0]
 [1 0 1 0 0]]


In [9]:
# Implementing cosine similarity
cosine_sim = cosine_similarity(count_matrix)

In [10]:
cosine_sim

array([[1. , 0. , 0. ],
       [0. , 1. , 0.5],
       [0. , 0.5, 1. ]])

In [11]:
# Giving Input Value for Book to check similar books
books_user_likes = "The Middle Stories"
def get_index_from_title(title):
    return books_df1[books_df1['Book.Title'] == books_user_likes]
books_index = get_index_from_title(books_user_likes)

In [12]:
# Getting List of Cosine Similarities for books
similar_books = list(cosine_sim)

In [13]:
# Sorting the Similar Books List in Descending Order
sorted_similar_books = sorted(similar_books, key=lambda x:x[1], reverse=True)

In [14]:
# Printing Similar Books
def get_title_from_index(index):
    return books_df1[books_df1.index == index]["Book.Title"].values
i=0
for books in sorted_similar_books:
    print(get_title_from_index(books[0]))
    i=i+1
    if i>15:
        break

['Classical Mythology']
['Classical Mythology']
[]


## We have given input value as 'The Middle Stories' and output is returned as 'Classical Mythology' for similar book